"""Export grants.db data as a PostgreSQL data script.

Run:  python migration/export_to_postgres.py
Writes migration/postgres/99_data.sql. Apply after 01/02/03:

    psql -d grants -f 01_schema.sql -f 02_functions_triggers.sql \
         -f 03_views.sql -f 99_data.sql

Expenditure triggers are disabled during the load so the existing audit log
and rollup migrate verbatim (instead of being regenerated with new
timestamps); identity sequences are then advanced past the migrated ids.
"""
import os
import sqlite3

HERE = os.path.dirname(os.path.abspath(__file__))
DB = os.path.join(os.path.dirname(HERE), "grants.db")
OUT = os.path.join(HERE, "postgres", "99_data.sql")

# (table, columns, boolean columns) in FK-safe load order
TABLES = [
    ("federal_agency", ["agency_id", "agency_name", "cgac_code", "aln_prefix"], []),
    ("pass_through_entity", ["pass_through_id", "pass_through_name", "pass_through_award_number"], []),
    ("subrecipient", ["subrecipient_id", "subrecipient_name", "subrecipient_uei"], []),
    ("department", ["department_id", "department_name"], []),
    ("fiscal_year", ["fiscal_year_id", "fy_label", "start_date", "end_date"], []),
    ("program", ["program_id", "aln", "program_title", "agency_id", "cluster_name",
                 "other_cluster_name", "is_clustered", "is_rd"],
     ["is_clustered", "is_rd"]),
    ("award", ["award_id", "fain_or_ptin", "identifier_type", "award_name", "program_id",
               "pass_through_id", "is_direct", "original_award_amount", "award_period_start",
               "award_period_end", "internal_gl_string", "award_type", "de_minimis_elected",
               "indirect_cost_rate"],
     ["is_direct", "de_minimis_elected"]),
    ("entity_profile", ["entity_id", "auditee_name", "auditee_uei", "auditee_ein",
                        "fiscal_year_end", "basis_of_accounting"], []),
    ("loan_balance", ["loan_balance_id", "award_id", "fiscal_year_id", "outstanding_balance"], []),
    ("sefa_note", ["note_id", "fiscal_year_id", "note_number", "note_title", "note_text"], []),
    ("app_user", ["user_id", "username", "display_name", "role", "password_salt",
                  "password_hash", "hash_algo", "hash_iterations", "is_active",
                  "created_at", "last_login"],
     ["is_active"]),
    ("login_audit", ["login_audit_id", "username", "success", "client_addr", "attempted_at"],
     ["success"]),
    ("expenditure", ["expenditure_id", "award_id", "fiscal_year_id", "department_id", "amount",
                     "transaction_date", "description", "amount_to_subrecipient",
                     "subrecipient_id", "is_adjustment", "doc_reference", "entered_by",
                     "entered_at"],
     ["is_adjustment"]),
    ("expenditure_audit_log", ["audit_id", "expenditure_id", "action", "old_amount", "new_amount",
                               "old_award_id", "new_award_id", "old_department_id",
                               "new_department_id", "old_transaction_date", "new_transaction_date",
                               "old_doc_reference", "new_doc_reference", "changed_by", "changed_at",
                               "old_award_balance", "new_award_balance"], []),
    ("department_spending", ["department_id", "award_id", "fiscal_year_id", "total_spent",
                             "total_to_subrecipients", "transaction_count", "last_updated"], []),
    ("award_document", ["document_id", "award_id", "file_name", "storage_path", "external_url",
                        "doc_type", "content_type", "file_size", "uploaded_by", "uploaded_at"], []),
]

# tables whose loads must not fire the expenditure triggers
DISABLE_TRIGGERS = {"expenditure", "expenditure_audit_log", "department_spending", "login_audit"}
IDENTITY_PK = {t: cols[0] for t, cols, _ in TABLES
               if t not in ("entity_profile", "department_spending")}


def lit(value, is_bool):
    if value is None:
        return "NULL"
    if is_bool:
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def main():
    con = sqlite3.connect(DB)
    lines = [
        "-- Generated by migration/export_to_postgres.py — data snapshot of grants.db",
        "BEGIN;",
        "SET session_replication_role = replica;  -- suspend triggers during load",
    ]
    for table, cols, bools in TABLES:
        rows = con.execute(
            "SELECT %s FROM %s" % (", ".join(cols), table)).fetchall()
        if not rows:
            continue
        lines.append("")
        lines.append("-- %s (%d rows)" % (table, len(rows)))
        for r in rows:
            vals = ", ".join(lit(v, c in bools) for v, c in zip(r, cols))
            overriding = " OVERRIDING SYSTEM VALUE" if table in IDENTITY_PK else ""
            lines.append("INSERT INTO %s (%s)%s VALUES (%s);"
                         % (table, ", ".join(cols), overriding, vals))
    lines.append("")
    lines.append("SET session_replication_role = DEFAULT;")
    lines.append("")
    lines.append("-- advance identity sequences past migrated ids")
    for table, pk in IDENTITY_PK.items():
        lines.append(
            "SELECT setval(pg_get_serial_sequence('%s', '%s'), "
            "COALESCE((SELECT MAX(%s) FROM %s), 1));" % (table, pk, pk, table))
    lines.append("COMMIT;")
    con.close()

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
