-- =============================================================================
-- SEFA Grant Tracking — PostgreSQL schema
-- Target: PostgreSQL 14+ (incl. Azure Database for PostgreSQL Flexible Server)
-- Translated from the SQLite schema (sql/01_schema.sql) with native types:
-- identities, NUMERIC(14,2) money, BOOLEAN flags, DATE/TIMESTAMPTZ.
-- Apply in order: 01_schema.sql -> 02_functions_triggers.sql -> 03_views.sql
--                 -> 99_data.sql (generated by migration/export_to_postgres.py)
-- =============================================================================

BEGIN;

CREATE TABLE federal_agency (
    agency_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_name  TEXT NOT NULL,
    cgac_code    TEXT,
    aln_prefix   TEXT
);

CREATE TABLE pass_through_entity (
    pass_through_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pass_through_name         TEXT NOT NULL,
    pass_through_award_number TEXT
);

CREATE TABLE subrecipient (
    subrecipient_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subrecipient_name TEXT NOT NULL,
    subrecipient_uei  TEXT
);

CREATE TABLE department (
    department_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name TEXT NOT NULL
);

CREATE TABLE fiscal_year (
    fiscal_year_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fy_label       TEXT NOT NULL,
    start_date     DATE NOT NULL,
    end_date       DATE NOT NULL,
    CHECK (end_date > start_date)
);

CREATE TABLE program (
    program_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aln                TEXT NOT NULL UNIQUE,
    program_title      TEXT NOT NULL,
    agency_id          BIGINT NOT NULL REFERENCES federal_agency(agency_id),
    cluster_name       TEXT,
    other_cluster_name TEXT,
    is_clustered       BOOLEAN NOT NULL DEFAULT FALSE,
    is_rd              BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE award (
    award_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fain_or_ptin          TEXT,
    identifier_type       TEXT CHECK (identifier_type IN ('FAIN', 'PASS_THROUGH')),
    award_name            TEXT,
    program_id            BIGINT NOT NULL REFERENCES program(program_id),
    pass_through_id       BIGINT REFERENCES pass_through_entity(pass_through_id),
    is_direct             BOOLEAN NOT NULL DEFAULT TRUE,
    original_award_amount NUMERIC(14, 2),
    award_period_start    DATE,
    award_period_end      DATE,
    internal_gl_string    TEXT,
    award_type            TEXT NOT NULL DEFAULT 'grant'
                          CHECK (award_type IN ('grant', 'cooperative_agreement',
                                                'loan', 'loan_guarantee', 'noncash')),
    de_minimis_elected    BOOLEAN NOT NULL DEFAULT FALSE,
    indirect_cost_rate    NUMERIC(6, 4)
);

CREATE TABLE expenditure (
    expenditure_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_id               BIGINT NOT NULL REFERENCES award(award_id),
    fiscal_year_id         BIGINT NOT NULL REFERENCES fiscal_year(fiscal_year_id),
    department_id          BIGINT REFERENCES department(department_id),
    amount                 NUMERIC(14, 2) NOT NULL,
    transaction_date       DATE NOT NULL,
    description            TEXT,
    amount_to_subrecipient NUMERIC(14, 2) NOT NULL DEFAULT 0,
    subrecipient_id        BIGINT REFERENCES subrecipient(subrecipient_id),
    is_adjustment          BOOLEAN NOT NULL DEFAULT FALSE,
    doc_reference          TEXT,
    entered_by             TEXT,
    entered_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Compliance tables (2 CFR 200.510(b), FAC submission)
-- ---------------------------------------------------------------------------

CREATE TABLE entity_profile (
    entity_id           SMALLINT PRIMARY KEY CHECK (entity_id = 1),
    auditee_name        TEXT NOT NULL,
    auditee_uei         TEXT,
    auditee_ein         TEXT,
    fiscal_year_end     TEXT,
    basis_of_accounting TEXT CHECK (basis_of_accounting IN ('CASH', 'ACCRUAL', 'MODIFIED_ACCRUAL'))
);

CREATE TABLE loan_balance (
    loan_balance_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_id            BIGINT NOT NULL REFERENCES award(award_id),
    fiscal_year_id      BIGINT NOT NULL REFERENCES fiscal_year(fiscal_year_id),
    outstanding_balance NUMERIC(14, 2) NOT NULL,
    UNIQUE (award_id, fiscal_year_id)
);

CREATE TABLE sefa_note (
    note_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fiscal_year_id BIGINT NOT NULL REFERENCES fiscal_year(fiscal_year_id),
    note_number    INTEGER,
    note_title     TEXT NOT NULL,
    note_text      TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- Paper-trail tables
-- ---------------------------------------------------------------------------

CREATE TABLE expenditure_audit_log (
    audit_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expenditure_id       BIGINT NOT NULL,
    action               TEXT NOT NULL CHECK (action IN ('INSERT', 'UPDATE', 'DELETE')),
    old_amount           NUMERIC(14, 2),
    new_amount           NUMERIC(14, 2),
    old_award_id         BIGINT,
    new_award_id         BIGINT,
    old_department_id    BIGINT,
    new_department_id    BIGINT,
    old_transaction_date DATE,
    new_transaction_date DATE,
    old_doc_reference    TEXT,
    new_doc_reference    TEXT,
    changed_by           TEXT,
    changed_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    old_award_balance    NUMERIC(14, 2),
    new_award_balance    NUMERIC(14, 2)
);

CREATE TABLE department_spending (
    department_id          BIGINT NOT NULL REFERENCES department(department_id),
    award_id               BIGINT NOT NULL REFERENCES award(award_id),
    fiscal_year_id         BIGINT NOT NULL REFERENCES fiscal_year(fiscal_year_id),
    total_spent            NUMERIC(14, 2) NOT NULL DEFAULT 0,
    total_to_subrecipients NUMERIC(14, 2) NOT NULL DEFAULT 0,
    transaction_count      INTEGER NOT NULL DEFAULT 0,
    last_updated           TIMESTAMPTZ,
    PRIMARY KEY (department_id, award_id, fiscal_year_id)
);

-- ---------------------------------------------------------------------------
-- Application users, sessions, documents
-- ---------------------------------------------------------------------------

CREATE TABLE app_user (
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        TEXT NOT NULL UNIQUE,
    display_name    TEXT NOT NULL,
    role            TEXT NOT NULL CHECK (role IN ('grant_manager', 'finance_admin', 'viewer')),
    password_salt   TEXT NOT NULL,
    password_hash   TEXT NOT NULL,
    hash_algo       TEXT NOT NULL DEFAULT 'pbkdf2_sha256',
    hash_iterations INTEGER NOT NULL DEFAULT 200000,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login      TIMESTAMPTZ
);

CREATE TABLE login_audit (
    login_audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       TEXT NOT NULL,
    success        BOOLEAN NOT NULL,
    client_addr    TEXT,
    attempted_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE app_session (
    token_hash   TEXT PRIMARY KEY,
    username     TEXT NOT NULL,
    display_name TEXT,
    role         TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE award_document (
    document_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    award_id     BIGINT NOT NULL REFERENCES award(award_id),
    file_name    TEXT NOT NULL,
    storage_path TEXT,
    external_url TEXT,
    doc_type     TEXT NOT NULL DEFAULT 'award_letter'
                 CHECK (doc_type IN ('award_letter', 'amendment', 'invoice', 'report', 'other')),
    content_type TEXT DEFAULT 'application/pdf',
    file_size    BIGINT,
    uploaded_by  TEXT,
    uploaded_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (storage_path IS NOT NULL OR external_url IS NOT NULL)
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

CREATE INDEX idx_expenditure_award      ON expenditure(award_id);
CREATE INDEX idx_expenditure_fy         ON expenditure(fiscal_year_id);
CREATE INDEX idx_expenditure_department ON expenditure(department_id);
CREATE INDEX idx_expenditure_txn_date   ON expenditure(transaction_date);
CREATE INDEX idx_award_program          ON award(program_id);
CREATE INDEX idx_program_agency         ON program(agency_id);
CREATE INDEX idx_audit_expenditure      ON expenditure_audit_log(expenditure_id);
CREATE INDEX idx_loan_balance_fy        ON loan_balance(fiscal_year_id);
CREATE INDEX idx_award_document_award   ON award_document(award_id);

COMMIT;
