-- =============================================================================
-- SEFA Grant Tracking Database — Master / Lookup Seed Data
-- City of Panama City, Florida (demo entity — fictional awards and amounts;
-- real ALNs and agencies). Florida local-government fiscal year: Oct 1–Sep 30.
-- Expenditure rows are generated by build_db.py so the triggers fire per-row.
-- =============================================================================

PRAGMA foreign_keys = ON;

INSERT INTO entity_profile (entity_id, auditee_name, auditee_uei, auditee_ein, fiscal_year_end, basis_of_accounting) VALUES
(1, 'City of Panama City, Florida', 'DEMO1UEI2345', '59-1234567', '09-30', 'MODIFIED_ACCRUAL');

INSERT INTO federal_agency (agency_id, agency_name, cgac_code, aln_prefix) VALUES
(1, 'U.S. Department of Transportation',            '069', '20'),
(2, 'U.S. Department of Justice',                   '015', '16'),
(3, 'U.S. Department of Housing and Urban Development', '086', '14'),
(4, 'U.S. Department of the Interior',              '014', '15'),
(5, 'U.S. Environmental Protection Agency',         '068', '66'),
(6, 'U.S. Department of Homeland Security',         '070', '97');

-- Florida state awarding agencies (SESFA, s. 215.97 F.S.; prefix = CSFA prefix)
INSERT INTO federal_agency (agency_id, agency_name, cgac_code, aln_prefix, agency_level) VALUES
(7,  'Florida Department of Transportation',           NULL, '55', 'STATE'),
(8,  'Florida Department of Environmental Protection', NULL, '37', 'STATE'),
(9,  'Florida Department of Commerce',                 NULL, '40', 'STATE'),
(10, 'Florida Division of Emergency Management',       NULL, '31', 'STATE'),
(11, 'Florida Department of State',                    NULL, '45', 'STATE');

INSERT INTO pass_through_entity (pass_through_id, pass_through_name, pass_through_award_number) VALUES
(1, 'Florida Department of Transportation',              'FDOT-AR-2024-117'),
(2, 'Florida Department of Law Enforcement',             'FDLE-JAG-24-882'),
(3, 'Florida Department of Environmental Protection',    'LWCF-25-041'),
(4, 'Florida DEP - Clean Water State Revolving Fund',    'CS12-0606-23');

INSERT INTO subrecipient (subrecipient_id, subrecipient_name, subrecipient_uei) VALUES
(1, 'Panhandle Housing Coalition',        'SUB1UEI00001'),
(2, 'Gulf Coast Community Action Agency', 'SUB2UEI00002'),
(3, 'Friends of Panama City Parks',       'SUB3UEI00003'),
(4, 'Emerald Coast Mobility Partners',    'SUB4UEI00004');

INSERT INTO department (department_id, department_name) VALUES
(1, 'Public Works & Utilities'),
(2, 'Police Department'),
(3, 'Community Redevelopment'),
(4, 'Emergency Management'),
(5, 'Transit & Mobility'),
(6, 'Parks & Recreation');

INSERT INTO fiscal_year (fiscal_year_id, fy_label, start_date, end_date) VALUES
(1, 'FY2024', '2023-10-01', '2024-09-30'),
(2, 'FY2025', '2024-10-01', '2025-09-30'),
(3, 'FY2026', '2025-10-01', '2026-09-30'),
(4, 'FY2027', '2026-10-01', '2027-09-30');  -- upcoming FY: budgets loaded, no activity yet

INSERT INTO program (program_id, aln, program_title, agency_id, cluster_name, other_cluster_name, is_clustered, is_rd) VALUES
(1, '20.205', 'Highway Planning and Construction',            1, 'Highway Planning and Construction Cluster', NULL, 1, 0),
(2, '20.507', 'Federal Transit Formula Grants',               1, 'Federal Transit Cluster',                    NULL, 1, 0),
(3, '16.738', 'Edward Byrne Memorial Justice Assistance Grant Program', 2, NULL,                              NULL, 0, 0),
(4, '20.600', 'State and Community Highway Safety',           1, 'Highway Safety Cluster',                     NULL, 1, 0),
(5, '14.218', 'Community Development Block Grants/Entitlement Grants', 3, 'CDBG - Entitlement Grants Cluster', NULL, 1, 0),
(6, '15.916', 'Outdoor Recreation - Acquisition, Development and Planning', 4, NULL,                          NULL, 0, 0),
(7, '66.458', 'Capitalization Grants for Clean Water State Revolving Funds', 5, 'Clean Water State Revolving Fund Cluster', NULL, 1, 0),
(8, '97.036', 'Disaster Grants - Public Assistance (Presidentially Declared Disasters)', 6, NULL, NULL, 0, 0);

-- Florida state programs — the aln column carries the CSFA number here
INSERT INTO program (program_id, aln, program_title, agency_id, cluster_name, other_cluster_name, is_clustered, is_rd) VALUES
(9,  '55.026', 'Transportation Regional Incentive Program (TRIP)',           7, NULL, NULL, 0, 0),
(10, '37.017', 'Florida Recreation Development Assistance Program (FRDAP)',  8, NULL, NULL, 0, 0),
(11, '37.076', 'Drinking Water State Revolving Fund Loan Program',           8, NULL, NULL, 0, 0),
(12, '40.038', 'Local Government Special Legislative Appropriation',         9, NULL, NULL, 0, 0),
(15, '31.066', 'Hurricane Loss Mitigation Program',                         10, NULL, NULL, 0, 0),
(16, '45.031', 'Historic Preservation Grants',                              11, NULL, NULL, 0, 0);

-- Additional federal programs
INSERT INTO program (program_id, aln, program_title, agency_id, cluster_name, other_cluster_name, is_clustered, is_rd) VALUES
(13, '66.818', 'Brownfields Assessment and Cleanup Cooperative Agreements',  5, NULL, NULL, 0, 0),
(14, '20.526', 'Buses and Bus Facilities Formula, Competitive, and Low/No Emissions Programs', 1, 'Federal Transit Cluster', NULL, 1, 0);

-- award_date is when the award was made; the period of performance often
-- begins later (e.g. awarded July 1, performance starts in the fall).
INSERT INTO award (award_id, fain_or_ptin, identifier_type, award_name, program_id, pass_through_id, is_direct,
                   original_award_amount, award_date, award_period_start, award_period_end, internal_gl_string,
                   award_type, state_award_type, de_minimis_elected, indirect_cost_rate) VALUES
(1,  'FDOT-AR-2024-117', 'PASS_THROUGH', 'Seagrass Avenue Corridor Reconstruction', 1, 1, 0,  8500000, '2023-07-01', '2023-10-01', '2027-09-30', '101-4300-55110', 'grant', NULL, 0, 0.0425),
(2,  '693JJ32460081',    'FAIN',         'Bridge Safety Inspection Program',        1, NULL, 1, 1200000, '2023-11-15', '2024-01-01', '2026-12-31', '101-4300-55112', 'grant', NULL, 1, NULL),
(3,  'FL-2024-014-00',   'FAIN',         'Bayside Trolley Fleet Modernization',      2, NULL, 1, 4750000, '2023-08-22', '2023-10-01', '2026-09-30', '208-4700-55200', 'grant', NULL, 0, 0.0380),
(4,  'FDLE-JAG-24-882',  'PASS_THROUGH', 'Community Policing Equipment & Outreach', 3, 2, 0,   650000, '2023-09-05', '2023-10-01', '2026-09-30', '110-5200-55310', 'grant', NULL, 1, NULL),
(5,  'FDOT-HS-24-311',   'PASS_THROUGH', 'Pedestrian & Bicycle Safety Campaign',    4, 1, 0,   400000, '2023-07-18', '2023-10-01', '2026-09-30', '110-5210-55320', 'grant', NULL, 1, NULL),
(6,  'B-24-MC-12-0021',  'FAIN',         'Osprey Point Neighborhood Revitalization CDBG', 5, NULL, 1, 3100000, '2024-07-01', '2024-10-01', '2027-09-30', '230-5600-55400', 'grant', NULL, 0, 0.0500),
(7,  'LWCF-25-041',      'PASS_THROUGH', 'Blue Heron Park Expansion (LWCF)',   6, 3, 0,  2750000, '2024-08-14', '2024-10-01', '2026-12-31', '240-5800-55500', 'grant', NULL, 1, NULL),
(8,  'CS12-0606-23',     'PASS_THROUGH', 'Pelican Bay Wastewater Plant Upgrade Loan', 7, 4, 0, 6000000, '2023-06-30', '2023-10-01', '2028-09-30', '502-4900-55600', 'loan', NULL, 0, NULL),
(9,  'FEMA-4734-DR-FL',  'FAIN',         'Hurricane Recovery - Public Assistance',  8, NULL, 1, 5200000, '2023-09-12', '2023-10-01', '2026-09-30', '101-4200-55700', 'grant', NULL, 1, NULL),
(10, 'FDOT-SR2S-26-042', 'PASS_THROUGH', 'Safe Routes to School Sidewalks',         1, 1, 0,   650000, '2025-07-01', '2025-10-01', '2027-09-30', '101-4300-55115', 'grant', NULL, 1, NULL),
-- State financial assistance (SESFA) — direct awards from Florida agencies
(11, 'TRIP-441509-1',    'STATE', 'Coastal Parkway Corridor TRIP Improvements',          9, NULL, 1, 2400000, '2024-07-01', '2024-09-01', '2027-08-31', '101-4300-55120', 'grant', 'state_grant_agreement',     0, NULL),
(12, 'FRDAP-A26188',     'STATE', 'Sandpiper Park Playground & Pier Renovation',    10, NULL, 1,  200000, '2025-08-20', '2025-10-01', '2027-09-30', '240-5800-55510', 'grant', 'state_grant_agreement',     0, NULL),
(13, 'DW120600-04',      'STATE', 'Northshore Water Main Replacement (DWSRF Loan)', 11, NULL, 1, 3500000, '2024-06-15', '2024-10-01', '2028-09-30', '502-4900-55610', 'loan',  'state_revolving_fund',      0, NULL),
(14, 'GAA-2026-LI-1234A','STATE', 'Downtown Marina Seawall Repair (GAA Line Item)', 12, NULL, 1, 1500000, '2025-07-01', '2025-07-01', '2027-06-30', '230-5600-55410', 'grant', 'legislative_appropriation', 0, NULL),
-- Round two of demo awards (federal + state) for a fuller portfolio
(15, 'BF-02D40025',      'FAIN',  'Former Cannery Site Brownfields Assessment',     13, NULL, 1,  500000, '2024-05-20', '2024-10-01', '2028-09-30', '230-5600-55420', 'cooperative_agreement', NULL, 1, NULL),
(16, 'FL-2026-031-00',   'FAIN',  'Low-Emission Bus Replacement Program',           14, NULL, 1, 1900000, '2025-06-10', '2025-10-01', '2028-09-30', '208-4700-55210', 'grant', NULL, 0, 0.0380),
(17, 'HLMP-26-088',      'STATE', 'Wind Retrofit Grants for Critical Facilities',   15, NULL, 1,  750000, '2025-05-01', '2025-07-01', '2027-06-30', '101-4200-55710', 'grant', 'state_grant_agreement', 0, NULL),
(18, 'SM-2026-1077',     'STATE', 'Old City Hall Facade Restoration (Small Matching)', 16, NULL, 1, 150000, '2025-06-25', '2025-07-01', '2026-06-30', '240-5800-55520', 'grant', 'state_grant_agreement', 0, NULL);

-- Outstanding loan balances at each fiscal year end (2 CFR 200.510(b)(5);
-- state SRF loan balances are reported on the SESFA as well)
INSERT INTO loan_balance (award_id, fiscal_year_id, outstanding_balance) VALUES
(8, 1, 1800000),
(8, 2, 3450000),
(8, 3, 4900000),
(13, 2,  600000),
(13, 3, 1750000);

-- General operating funds (basic tracker; one budget row per fund per FY)
INSERT INTO operating_fund (fund_id, fund_code, fund_name, fiscal_year_id, budget_amount, notes) VALUES
(1, '001', 'General Fund',               2, 46200000, 'Adopted FY2025 operating budget'),
(2, '001', 'General Fund',               3, 48500000, 'Adopted FY2026 operating budget'),
(3, '401', 'Water & Sewer Utility Fund', 3, 22800000, 'Enterprise fund — rates and charges for services'),
(4, '101', 'Transportation Fund',        3,  6400000, 'Local option gas tax and mobility fees'),
(5, '001', 'General Fund',               1, 44100000, 'Adopted FY2024 operating budget'),
(6, '401', 'Water & Sewer Utility Fund', 2, 21500000, 'Enterprise fund — rates and charges for services');

-- Community Redevelopment Agency districts (Ch. 163 Part III, F.S.)
-- Baseline = taxable value frozen in the base year; the increment above it
-- generates the TIF revenue deposited to each district's trust fund.
INSERT INTO cra_district (district_id, district_name, established_year, sunset_year,
                          base_year, base_taxable_value, current_taxable_value, notes) VALUES
(1, 'Downtown',       1984, 2039, 1984, 38500000, 112400000, 'Core commercial district — streetscapes, facades, marina'),
(2, 'St. Andrews',    1989, 2044, 1989, 21700000,  64800000, 'Historic waterfront village — corridor and public realm'),
(3, 'Downtown North', 1995, 2050, 1995, 17300000,  41200000, 'Neighborhood revitalization — housing and gateway corridors'),
(4, 'Millville',      2001, 2051, 2001, 12600000,  27900000, 'Industrial-heritage neighborhood — housing rehab and waterfront park');

-- District trust-fund funding sources (per adopted CRA budget)
INSERT INTO cra_funding_source (district_id, source_name, source_type, annual_amount, notes) VALUES
(1, 'City tax increment contribution',            'tax_increment',       330000, '95% of city millage on the increment'),
(1, 'County tax increment contribution',          'county_contribution', 300000, '95% of county millage on the increment'),
(1, 'Downtown parking revenue transfer',          'general_fund',         60000, NULL),
(1, 'Trust fund interest earnings',               'interest',             12000, NULL),
(2, 'City tax increment contribution',            'tax_increment',       185000, '95% of city millage on the increment'),
(2, 'County tax increment contribution',          'county_contribution', 170000, '95% of county millage on the increment'),
(2, 'CDBG pass-through — facade & public realm',  'grant',                75000, NULL),
(2, 'Trust fund interest earnings',               'interest',              8000, NULL),
(3, 'City tax increment contribution',            'tax_increment',       108000, '95% of city millage on the increment'),
(3, 'County tax increment contribution',          'county_contribution',  98000, '95% of county millage on the increment'),
(3, 'CDBG entitlement pass-through — housing',    'grant',                90000, NULL),
(3, 'Trust fund interest earnings',               'interest',              5000, NULL),
(4, 'City tax increment contribution',            'tax_increment',        68000, '95% of city millage on the increment'),
(4, 'County tax increment contribution',          'county_contribution',  62000, '95% of county millage on the increment'),
(4, 'FRDAP state grant — waterfront park',        'grant',                50000, NULL),
(4, 'Trust fund interest earnings',               'interest',              3500, NULL);

INSERT INTO cra_project (project_id, district_id, project_code, project_name, category,
                         project_manager, status, budget_amount, start_date, target_completion) VALUES
(1,  1, 'CRA-DT-001', 'Harmon Avenue Streetscape Phase II',       'streetscape',         'Maria Garcia',    'underway', 1400000, '2024-04-01', '2026-12-31'),
(2,  1, 'CRA-DT-002', 'Commercial Facade Grant Program',          'business_assistance', 'Dana Williams',   'underway',  350000, '2023-10-01', '2027-09-30'),
(3,  1, 'CRA-DT-003', 'Marina District Parking Improvements',     'infrastructure',      'James Chen',      'planned',   900000, '2026-10-01', '2028-06-30'),
(4,  2, 'CRA-SA-001', 'Waterfront Pavilion & Pier Repairs',       'parks_public_space',  'Rachel Thompson', 'underway',  650000, '2024-06-01', '2026-09-30'),
(5,  2, 'CRA-SA-002', 'Bayview Avenue Lighting & Crosswalks',     'streetscape',         'Maria Garcia',    'complete',  240000, '2023-11-01', '2025-02-28'),
(6,  2, 'CRA-SA-003', 'Small Business Rent & Buildout Assistance','business_assistance', 'Kiran Patel',     'underway',  180000, '2025-01-15', '2027-12-31'),
(7,  3, 'CRA-DN-001', 'Downtown North Housing Rehabilitation',    'housing',             'Dana Williams',   'underway',  450000, '2024-01-15', '2027-03-31'),
(8,  3, 'CRA-DN-002', 'Gateway Signage & Corridor Landscaping',   'streetscape',         'James Chen',      'complete',  150000, '2023-11-01', '2025-05-31'),
(9,  3, 'CRA-DN-003', 'Neighborhood Park Splash Pad',             'parks_public_space',  'Rachel Thompson', 'planned',   220000, '2026-11-01', '2027-08-31'),
(10, 4, 'CRA-MV-001', 'Millville Waterfront Park Improvements',   'parks_public_space',  'Kiran Patel',     'underway',  320000, '2024-09-01', '2026-12-31'),
(11, 4, 'CRA-MV-002', 'Owner-Occupied Housing Repair Program',    'housing',             'Dana Williams',   'underway',  200000, '2024-10-01', '2027-09-30');

-- How each approved project budget is funded (capped at the budget by trigger)
INSERT INTO cra_project_funding (project_id, source_name, source_type, amount) VALUES
(1,  'Redevelopment trust fund (TIF)',            'tax_increment', 1000000),
(1,  'FDOT transportation alternatives grant',    'grant',          400000),
(2,  'Redevelopment trust fund (TIF)',            'tax_increment',  350000),
(3,  'Redevelopment trust fund (TIF)',            'tax_increment',  650000),
(3,  'Downtown parking revenue transfer',         'general_fund',   250000),
(4,  'Redevelopment trust fund (TIF)',            'tax_increment',  450000),
(4,  'Tourist development council grant',         'grant',          200000),
(5,  'Redevelopment trust fund (TIF)',            'tax_increment',  240000),
(6,  'Redevelopment trust fund (TIF)',            'tax_increment',  130000),
(6,  'Participating landlord match',              'private_match',   50000),
(7,  'Redevelopment trust fund (TIF)',            'tax_increment',  270000),
(7,  'CDBG entitlement pass-through',             'grant',          180000),
(8,  'Redevelopment trust fund (TIF)',            'tax_increment',  150000),
(9,  'Redevelopment trust fund (TIF)',            'tax_increment',  160000),
(9,  'General fund parks match',                  'general_fund',    60000),
(10, 'Redevelopment trust fund (TIF)',            'tax_increment',  220000),
(10, 'FRDAP state grant',                         'grant',          100000),
(11, 'Redevelopment trust fund (TIF)',            'tax_increment',  150000),
(11, 'SHIP state housing funds',                  'grant',           50000);

-- Community engagement held per project and the action taken in response.
-- Projects 2 and 8 intentionally have no rows (engagement_done = 'No').
INSERT INTO cra_engagement (project_id, engagement_type, engagement_date, title,
                            participants, summary, action_taken, entered_by) VALUES
(1,  'survey',         '2024-02-10', 'Downtown streetscape design survey',        412,
     'Online + paper survey on lane widths, trees, parking, and sidewalk cafes.',
     'Added mid-block crossings and doubled shade-tree count in the 60% design.', 'mgarcia'),
(1,  'public_meeting', '2024-03-05', 'Streetscape design open house',              85,
     'Boards and Q&A at City Hall on the preferred concept.',
     'Parking layout revised to keep 22 on-street spaces during construction.',   'mgarcia'),
(3,  'public_meeting', '2026-05-14', 'Marina parking public workshop',             47,
     'Options workshop: surface lots vs. parking structure.',
     'Garage option deferred; phased surface-lot plan adopted by the CRA board.', 'jchen'),
(4,  'charrette',      '2024-04-20', 'Waterfront pavilion design charrette',       63,
     'Hands-on design session with residents and charter captains.',
     'Pier railing height revised and dedicated fishing stations added to plans.','rthompson'),
(5,  'survey',         '2023-09-12', 'Corridor lighting priorities survey',       188,
     'Residents ranked lighting, crosswalks, and landscaping priorities.',
     'Warm-white fixtures selected; two additional crosswalks added to scope.',   'mgarcia'),
(6,  'workshop',       '2025-02-06', 'Small business assistance workshop',         34,
     'Walk-through of the rent/buildout program with corridor merchants.',
     'Application simplified to two pages; monthly rent cap raised.',             'kpatel'),
(7,  'survey',         '2024-01-30', 'Housing conditions & needs survey',         265,
     'Door-to-door and mail survey of owner-occupied homes in the district.',
     'Roof and HVAC repairs prioritized in the program guidelines.',              'dwilliams'),
(9,  'survey',         '2026-06-15', 'Neighborhood park amenities survey',        156,
     'Ranked-choice survey of park amenities for the new pocket park.',
     'Splash pad chosen over skate spot; shade sails added to the design.',       'rthompson'),
(10, 'public_meeting', '2024-08-22', 'Waterfront park community meeting',          58,
     'Concept review at the community center; boaters and anglers attended.',
     'Kayak launch added; boat-trailer parking retained in the final plan.',      'kpatel'),
(11, 'survey',         '2024-11-05', 'Owner-occupied repair interest survey',      97,
     'Interest and income pre-screening survey for the repair program.',
     'Income limit set at 120% AMI; waitlist lottery adopted for fairness.',      'dwilliams');

-- SEFA notes (2 CFR 200.510(b)(6))
INSERT INTO sefa_note (fiscal_year_id, note_number, note_title, note_text) VALUES
(3, 1, 'Basis of Presentation',
 'The accompanying Schedule of Expenditures of Federal Awards includes the federal award activity of the City of Panama City, Florida under programs of the federal government for the year ended September 30, 2026, presented on the modified accrual basis of accounting in accordance with 2 CFR Part 200, Uniform Guidance.'),
(3, 2, 'Indirect Cost Rate',
 'For awards flagged de_minimis_elected, the City has elected to use the 10 percent de minimis indirect cost rate allowed under 2 CFR 200.414(f). Other awards use the negotiated indirect cost rate shown on the award record.'),
(3, 3, 'Loan Programs',
 'The Clean Water State Revolving Fund loan (ALN 66.458) balance outstanding at September 30, 2026 was $4,900,000. Loan balances are reported in the loan_balance table by fiscal year as required by 2 CFR 200.510(b)(5).');

-- =============================================================================
-- Revenue tracker — city revenue streams (FL Uniform Accounting System codes)
-- mapped to the municipal ledger: General Fund, Enterprise (user fees), and
-- Special Revenue & Restricted. Receipts are generated by build_db.py so the
-- validation triggers fire per-row; seasonality curves are seeded there too.
-- =============================================================================

INSERT INTO revenue_stream (stream_id, account_code, stream_name, fund_type, collector, notes) VALUES
-- General Fund
(1,  '311.000', 'Ad Valorem Property Taxes',            'general',         'County Tax Collector',      'Driven by certified property valuations; DR-422 millage'),
(2,  '312.600', 'Local Option Sales Tax',               'general',         'Florida DOR clearinghouse', 'Discretionary sales surtax allocation'),
(3,  '313.100', 'Franchise Fees',                       'general',         'Utility franchisees',       'Electricity, gas, and solid waste franchise agreements'),
(4,  '314.000', 'Utility Service Taxes',                'general',         'Utility billing',           'Electricity, gas, water public service taxes'),
(5,  '315.000', 'Communications Services Tax',          'general',         'Florida DOR clearinghouse', NULL),
(6,  '321.000', 'Business Tax Receipts',                'general',         'City Clerk',                'Local business tax; renewals due September 30'),
(7,  '322.000', 'Building Permits & Inspection Fees',   'general',         'Development Services',      NULL),
-- Enterprise funds (user fees)
(8,  '343.300', 'Water & Sewer User Fees',              'enterprise',      'Utility billing / lockbox', NULL),
(9,  '343.400', 'Solid Waste Collection Fees',          'enterprise',      'Utility billing / lockbox', NULL),
(10, '347.500', 'Marina & Docking Fees',                'enterprise',      'Marina office',             NULL),
-- Special revenue & restricted
(11, '335.180', 'Half-Cent Sales Tax (state-shared)',   'special_revenue', 'Florida DOR clearinghouse', 'Local Government Half-cent Sales Tax Program'),
(12, '335.120', 'State Revenue Sharing',                'special_revenue', 'Florida DOR clearinghouse', 'Municipal Revenue Sharing Program, s. 218.20 F.S.'),
(13, '312.410', 'Local Option Fuel Tax',                'special_revenue', 'Florida DOR clearinghouse', NULL),
(14, '338.100', 'CRA Tax Increment Contributions',      'special_revenue', 'City / County remittance',  'Deposits to the four redevelopment trust funds'),
(15, '331.000', 'Federal & State Grant Reimbursements', 'special_revenue', 'Grantor agencies',          'Detail tracked per-award in the grants module');

-- Budgeted FY amounts per stream (FY2024–FY2026 history + upcoming FY2027)
INSERT INTO revenue_budget (stream_id, fiscal_year_id, budgeted_amount) VALUES
(1, 1, 19530000), (1, 2, 20265000), (1, 3, 21000000), (1, 4, 21840000),
(2, 1,  5394000), (2, 2,  5597000), (2, 3,  5800000), (2, 4,  6032000),
(3, 1,  2418000), (3, 2,  2509000), (3, 3,  2600000), (3, 4,  2704000),
(4, 1,  4278000), (4, 2,  4439000), (4, 3,  4600000), (4, 4,  4784000),
(5, 1,  1767000), (5, 2,  1834000), (5, 3,  1900000), (5, 4,  1976000),
(6, 1,   605000), (6, 2,   627000), (6, 3,   650000), (6, 4,   676000),
(7, 1,  2604000), (7, 2,  2702000), (7, 3,  2800000), (7, 4,  2912000),
(8, 1, 13485000), (8, 2, 13993000), (8, 3, 14500000), (8, 4, 15080000),
(9, 1,  5208000), (9, 2,  5404000), (9, 3,  5600000), (9, 4,  5824000),
(10, 1, 1023000), (10, 2, 1062000), (10, 3, 1100000), (10, 4, 1144000),
(11, 1, 4557000), (11, 2, 4729000), (11, 3, 4900000), (11, 4, 5096000),
(12, 1, 2139000), (12, 2, 2220000), (12, 3, 2300000), (12, 4, 2392000),
(13, 1, 1488000), (13, 2, 1544000), (13, 3, 1600000), (13, 4, 1664000),
(14, 1, 1246000), (14, 2, 1293000), (14, 3, 1340000), (14, 4, 1394000),
(15, 1, 7626000), (15, 2, 7913000), (15, 3, 8200000), (15, 4, 8528000);

-- =============================================================================
-- Revenue integrity initiatives
-- =============================================================================

-- Business tax receipt compliance review (Ch. 205, F.S.)
INSERT INTO btr_case (case_id, business_name, business_address, case_status,
                      identified_date, notice_date, estimated_annual_tax,
                      collected_amount, notes, entered_by) VALUES
(1, 'Gulf Breeze Detailing LLC',        '1240 Harmon Ave',            'identified',  '2026-06-12', NULL,        158,   0, 'Mobile detailing operating from a commercial bay; no BTR on file', 'kpatel'),
(2, 'Sandbar Vacation Rentals',         '318 Bayview Ave',            'notice_sent', '2026-05-20', '2026-06-02', 312,   0, 'Six listed units; short-term rental registration also pending',    'kpatel'),
(3, 'Pelican Point Charters',           'Slip 14, City Marina',       'notice_sent', '2026-07-08', '2026-07-15', 264,   0, NULL,                                                                'dwilliams'),
(4, 'Shoreline Web Design',             '92 Osprey Point Rd',         'registered',  '2026-04-11', '2026-04-25',  79,  79, 'Registered and paid after first notice',                           'kpatel'),
(5, 'Harbor Light Ministries Thrift',   '507 Millville Ave',          'exempt',      '2026-05-05', NULL,           0,   0, 'Nonprofit exemption verified under s. 205.192',                    'dwilliams'),
(6, 'Coastal Craft Coffee (food truck)','Various — event circuit',    'identified',  '2026-08-10', NULL,         132,   0, 'Operates at city events; needs mobile vendor BTR',                 'mgarcia');

-- Indirect cost allocation plan: FY2026 adopted; FY2027 proposed (+~5%),
-- under review so enterprise and grant operations carry their share of
-- central administrative costs.
INSERT INTO icap_allocation (fiscal_year_id, plan_status, central_service, paying_fund, allocation_basis, annual_amount) VALUES
(3, 'adopted', 'Human Resources', 'Water & Sewer Utility Fund', 'FTEs supported',     118000),
(3, 'adopted', 'Information Technology', 'Water & Sewer Utility Fund', 'devices & seats', 142000),
(3, 'adopted', 'Legal',           'Water & Sewer Utility Fund', 'hours logged',        58000),
(3, 'adopted', 'City Manager',    'Water & Sewer Utility Fund', 'budget share',        84000),
(3, 'adopted', 'City Clerk',      'Water & Sewer Utility Fund', 'agenda items',        24000),
(3, 'adopted', 'Finance',         'Water & Sewer Utility Fund', 'transaction volume', 187000),
(3, 'adopted', 'Human Resources', 'Solid Waste Fund',           'FTEs supported',      46000),
(3, 'adopted', 'Information Technology', 'Solid Waste Fund',    'devices & seats',     51000),
(3, 'adopted', 'Legal',           'Solid Waste Fund',           'hours logged',        18000),
(3, 'adopted', 'City Manager',    'Solid Waste Fund',           'budget share',        30000),
(3, 'adopted', 'City Clerk',      'Solid Waste Fund',           'agenda items',         9000),
(3, 'adopted', 'Finance',         'Solid Waste Fund',           'transaction volume',  72000),
(3, 'adopted', 'Human Resources', 'Grant-funded programs',      'FTEs supported',      22000),
(3, 'adopted', 'Information Technology', 'Grant-funded programs', 'devices & seats',   34000),
(3, 'adopted', 'Legal',           'Grant-funded programs',      'hours logged',        12000),
(3, 'adopted', 'Finance',         'Grant-funded programs',      'transaction volume',  98000),
(3, 'adopted', 'Finance',         'CRA districts',              'transaction volume',  28000),
(3, 'adopted', 'Legal',           'CRA districts',              'hours logged',        15000),
(3, 'adopted', 'City Manager',    'CRA districts',              'budget share',        18000),
(4, 'proposed', 'Human Resources', 'Water & Sewer Utility Fund', 'FTEs supported',     124000),
(4, 'proposed', 'Information Technology', 'Water & Sewer Utility Fund', 'devices & seats', 149000),
(4, 'proposed', 'Legal',           'Water & Sewer Utility Fund', 'hours logged',        61000),
(4, 'proposed', 'City Manager',    'Water & Sewer Utility Fund', 'budget share',        88000),
(4, 'proposed', 'City Clerk',      'Water & Sewer Utility Fund', 'agenda items',        25000),
(4, 'proposed', 'Finance',         'Water & Sewer Utility Fund', 'transaction volume', 196000),
(4, 'proposed', 'Human Resources', 'Solid Waste Fund',           'FTEs supported',      48000),
(4, 'proposed', 'Information Technology', 'Solid Waste Fund',    'devices & seats',     54000),
(4, 'proposed', 'Legal',           'Solid Waste Fund',           'hours logged',        19000),
(4, 'proposed', 'City Manager',    'Solid Waste Fund',           'budget share',        32000),
(4, 'proposed', 'City Clerk',      'Solid Waste Fund',           'agenda items',         9500),
(4, 'proposed', 'Finance',         'Solid Waste Fund',           'transaction volume',  76000),
(4, 'proposed', 'Human Resources', 'Grant-funded programs',      'FTEs supported',      23000),
(4, 'proposed', 'Information Technology', 'Grant-funded programs', 'devices & seats',   36000),
(4, 'proposed', 'Legal',           'Grant-funded programs',      'hours logged',        13000),
(4, 'proposed', 'Finance',         'Grant-funded programs',      'transaction volume', 103000),
(4, 'proposed', 'Finance',         'CRA districts',              'transaction volume',  29500),
(4, 'proposed', 'Legal',           'CRA districts',              'hours logged',        16000),
(4, 'proposed', 'City Manager',    'CRA districts',              'budget share',        19000);
