-- =============================================================================
-- SEFA Grant Tracking Database — Master / Lookup Seed Data
-- City of Pelican Shores, Florida (demo entity — fictional awards and amounts;
-- real ALNs and agencies). Florida local-government fiscal year: Oct 1–Sep 30.
-- Expenditure rows are generated by build_db.py so the triggers fire per-row.
-- =============================================================================

PRAGMA foreign_keys = ON;

INSERT INTO entity_profile (entity_id, auditee_name, auditee_uei, auditee_ein, fiscal_year_end, basis_of_accounting) VALUES
(1, 'City of Pelican Shores, Florida', 'DEMO1UEI2345', '59-1234567', '09-30', 'MODIFIED_ACCRUAL');

INSERT INTO federal_agency (agency_id, agency_name, cgac_code, aln_prefix) VALUES
(1, 'U.S. Department of Transportation',            '069', '20'),
(2, 'U.S. Department of Justice',                   '015', '16'),
(3, 'U.S. Department of Housing and Urban Development', '086', '14'),
(4, 'U.S. Department of the Interior',              '014', '15'),
(5, 'U.S. Environmental Protection Agency',         '068', '66'),
(6, 'U.S. Department of Homeland Security',         '070', '97');

-- Florida state awarding agencies (SESFA, s. 215.97 F.S.; prefix = CSFA prefix)
INSERT INTO federal_agency (agency_id, agency_name, cgac_code, aln_prefix, agency_level) VALUES
(7, 'Florida Department of Transportation',           NULL, '55', 'STATE'),
(8, 'Florida Department of Environmental Protection', NULL, '37', 'STATE'),
(9, 'Florida Department of Commerce',                 NULL, '40', 'STATE');

INSERT INTO pass_through_entity (pass_through_id, pass_through_name, pass_through_award_number) VALUES
(1, 'Florida Department of Transportation',              'FDOT-AR-2024-117'),
(2, 'Florida Department of Law Enforcement',             'FDLE-JAG-24-882'),
(3, 'Florida Department of Environmental Protection',    'LWCF-25-041'),
(4, 'Florida DEP - Clean Water State Revolving Fund',    'CS12-0606-23');

INSERT INTO subrecipient (subrecipient_id, subrecipient_name, subrecipient_uei) VALUES
(1, 'Panhandle Housing Coalition',        'SUB1UEI00001'),
(2, 'Gulf Coast Community Action Agency', 'SUB2UEI00002'),
(3, 'Friends of Pelican Shores Parks',       'SUB3UEI00003'),
(4, 'Emerald Coast Mobility Partners',    'SUB4UEI00004');

INSERT INTO department (department_id, department_name) VALUES
(1, 'Public Works & Utilities'),
(2, 'Police Department'),
(3, 'Community Redevelopment'),
(4, 'Emergency Management'),
(5, 'Transit & Mobility'),
(6, 'Parks & Recreation');

INSERT INTO fiscal_year (fiscal_year_id, fy_label, start_date, end_date) VALUES
(1, 'FY2024', '2023-10-01', '2024-09-30'),
(2, 'FY2025', '2024-10-01', '2025-09-30'),
(3, 'FY2026', '2025-10-01', '2026-09-30');

INSERT INTO program (program_id, aln, program_title, agency_id, cluster_name, other_cluster_name, is_clustered, is_rd) VALUES
(1, '20.205', 'Highway Planning and Construction',            1, 'Highway Planning and Construction Cluster', NULL, 1, 0),
(2, '20.507', 'Federal Transit Formula Grants',               1, 'Federal Transit Cluster',                    NULL, 1, 0),
(3, '16.738', 'Edward Byrne Memorial Justice Assistance Grant Program', 2, NULL,                              NULL, 0, 0),
(4, '20.600', 'State and Community Highway Safety',           1, 'Highway Safety Cluster',                     NULL, 1, 0),
(5, '14.218', 'Community Development Block Grants/Entitlement Grants', 3, 'CDBG - Entitlement Grants Cluster', NULL, 1, 0),
(6, '15.916', 'Outdoor Recreation - Acquisition, Development and Planning', 4, NULL,                          NULL, 0, 0),
(7, '66.458', 'Capitalization Grants for Clean Water State Revolving Funds', 5, 'Clean Water State Revolving Fund Cluster', NULL, 1, 0),
(8, '97.036', 'Disaster Grants - Public Assistance (Presidentially Declared Disasters)', 6, NULL, NULL, 0, 0);

-- Florida state programs — the aln column carries the CSFA number here
INSERT INTO program (program_id, aln, program_title, agency_id, cluster_name, other_cluster_name, is_clustered, is_rd) VALUES
(9,  '55.026', 'Transportation Regional Incentive Program (TRIP)',           7, NULL, NULL, 0, 0),
(10, '37.017', 'Florida Recreation Development Assistance Program (FRDAP)',  8, NULL, NULL, 0, 0),
(11, '37.076', 'Drinking Water State Revolving Fund Loan Program',           8, NULL, NULL, 0, 0),
(12, '40.038', 'Local Government Special Legislative Appropriation',         9, NULL, NULL, 0, 0);

-- award_date is when the award was made; the period of performance often
-- begins later (e.g. awarded July 1, performance starts in the fall).
INSERT INTO award (award_id, fain_or_ptin, identifier_type, award_name, program_id, pass_through_id, is_direct,
                   original_award_amount, award_date, award_period_start, award_period_end, internal_gl_string,
                   award_type, state_award_type, de_minimis_elected, indirect_cost_rate) VALUES
(1,  'FDOT-AR-2024-117', 'PASS_THROUGH', 'Seagrass Avenue Corridor Reconstruction', 1, 1, 0,  8500000, '2023-07-01', '2023-10-01', '2027-09-30', '101-4300-55110', 'grant', NULL, 0, 0.0425),
(2,  '693JJ32460081',    'FAIN',         'Bridge Safety Inspection Program',        1, NULL, 1, 1200000, '2023-11-15', '2024-01-01', '2026-12-31', '101-4300-55112', 'grant', NULL, 1, NULL),
(3,  'FL-2024-014-00',   'FAIN',         'Bayside Trolley Fleet Modernization',      2, NULL, 1, 4750000, '2023-08-22', '2023-10-01', '2026-09-30', '208-4700-55200', 'grant', NULL, 0, 0.0380),
(4,  'FDLE-JAG-24-882',  'PASS_THROUGH', 'Community Policing Equipment & Outreach', 3, 2, 0,   650000, '2023-09-05', '2023-10-01', '2026-09-30', '110-5200-55310', 'grant', NULL, 1, NULL),
(5,  'FDOT-HS-24-311',   'PASS_THROUGH', 'Pedestrian & Bicycle Safety Campaign',    4, 1, 0,   400000, '2023-07-18', '2023-10-01', '2026-09-30', '110-5210-55320', 'grant', NULL, 1, NULL),
(6,  'B-24-MC-12-0021',  'FAIN',         'Osprey Point Neighborhood Revitalization CDBG', 5, NULL, 1, 3100000, '2024-07-01', '2024-10-01', '2027-09-30', '230-5600-55400', 'grant', NULL, 0, 0.0500),
(7,  'LWCF-25-041',      'PASS_THROUGH', 'Blue Heron Park Expansion (LWCF)',   6, 3, 0,  2750000, '2024-08-14', '2024-10-01', '2026-12-31', '240-5800-55500', 'grant', NULL, 1, NULL),
(8,  'CS12-0606-23',     'PASS_THROUGH', 'Pelican Bay Wastewater Plant Upgrade Loan', 7, 4, 0, 6000000, '2023-06-30', '2023-10-01', '2028-09-30', '502-4900-55600', 'loan', NULL, 0, NULL),
(9,  'FEMA-4734-DR-FL',  'FAIN',         'Hurricane Recovery - Public Assistance',  8, NULL, 1, 5200000, '2023-09-12', '2023-10-01', '2026-09-30', '101-4200-55700', 'grant', NULL, 1, NULL),
(10, 'FDOT-SR2S-26-042', 'PASS_THROUGH', 'Safe Routes to School Sidewalks',         1, 1, 0,   650000, '2025-07-01', '2025-10-01', '2027-09-30', '101-4300-55115', 'grant', NULL, 1, NULL),
-- State financial assistance (SESFA) — direct awards from Florida agencies
(11, 'TRIP-441509-1',    'STATE', 'Coastal Parkway Corridor TRIP Improvements',          9, NULL, 1, 2400000, '2024-07-01', '2024-09-01', '2027-08-31', '101-4300-55120', 'grant', 'state_grant_agreement',     0, NULL),
(12, 'FRDAP-A26188',     'STATE', 'Sandpiper Park Playground & Pier Renovation',    10, NULL, 1,  200000, '2025-08-20', '2025-10-01', '2027-09-30', '240-5800-55510', 'grant', 'state_grant_agreement',     0, NULL),
(13, 'DW120600-04',      'STATE', 'Northshore Water Main Replacement (DWSRF Loan)', 11, NULL, 1, 3500000, '2024-06-15', '2024-10-01', '2028-09-30', '502-4900-55610', 'loan',  'state_revolving_fund',      0, NULL),
(14, 'GAA-2026-LI-1234A','STATE', 'Downtown Marina Seawall Repair (GAA Line Item)', 12, NULL, 1, 1500000, '2025-07-01', '2025-07-01', '2027-06-30', '230-5600-55410', 'grant', 'legislative_appropriation', 0, NULL);

-- Outstanding loan balances at each fiscal year end (2 CFR 200.510(b)(5);
-- state SRF loan balances are reported on the SESFA as well)
INSERT INTO loan_balance (award_id, fiscal_year_id, outstanding_balance) VALUES
(8, 1, 1800000),
(8, 2, 3450000),
(8, 3, 4900000),
(13, 2,  600000),
(13, 3, 1750000);

-- General operating funds (basic tracker; one budget row per fund per FY)
INSERT INTO operating_fund (fund_id, fund_code, fund_name, fiscal_year_id, budget_amount, notes) VALUES
(1, '001', 'General Fund',               2, 46200000, 'Adopted FY2025 operating budget'),
(2, '001', 'General Fund',               3, 48500000, 'Adopted FY2026 operating budget'),
(3, '401', 'Water & Sewer Utility Fund', 3, 22800000, 'Enterprise fund — rates and charges for services'),
(4, '101', 'Transportation Fund',        3,  6400000, 'Local option gas tax and mobility fees');

-- SEFA notes (2 CFR 200.510(b)(6))
INSERT INTO sefa_note (fiscal_year_id, note_number, note_title, note_text) VALUES
(3, 1, 'Basis of Presentation',
 'The accompanying Schedule of Expenditures of Federal Awards includes the federal award activity of the City of Pelican Shores, Florida under programs of the federal government for the year ended September 30, 2026, presented on the modified accrual basis of accounting in accordance with 2 CFR Part 200, Uniform Guidance.'),
(3, 2, 'Indirect Cost Rate',
 'For awards flagged de_minimis_elected, the City has elected to use the 10 percent de minimis indirect cost rate allowed under 2 CFR 200.414(f). Other awards use the negotiated indirect cost rate shown on the award record.'),
(3, 3, 'Loan Programs',
 'The Clean Water State Revolving Fund loan (ALN 66.458) balance outstanding at September 30, 2026 was $4,900,000. Loan balances are reported in the loan_balance table by fiscal year as required by 2 CFR 200.510(b)(5).');
